import type { Metadata } from "next";
import "../globals.css";
import { k2d } from "../font";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "ShopSystem",
  description: "Generated by create next app",
};

export default async function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${k2d.className}`}>
        {children} <Toaster richColors position="bottom-center" />
      </body>
    </html>
  );
}
