import type { Metadata } from "next";
import { k2d } from "../font";
import "../globals.css";
import Navbar from "@/components/navbar";

export const metadata: Metadata = {
  title: "ShopSystem",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${k2d.className}`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
